modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/Slab-Machines/issues"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="slabmachines"
version="${file.jarVersion}"
displayName="Slab Machines"
displayURL="https://www.curseforge.com/minecraft/mc-mods/slab-machines"
authors="Mrbysco"
description='''
Machines but as a slab
'''
[[dependencies.slabmachines]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.slabmachines]]
modId="neoforge"
type="required"
versionRange="[20.6.78-beta,)"
ordering="NONE"
side="BOTH"